version: '3'
services:
  mongo:
    container_name: container-mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zrain123
      MONGO_INITDB_DATABASE: email_auth

    volumes:
      - ./mongo-initialize.js:/docker-entrypoint-initdb.d/mongo-initialize.js:ro

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass "zrain123"
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  mongodb:
  redisDB: